databases:
  - name: portfolio-db
    plan: free
    databaseName: personal_website
    user: portfolio_user

services:
  - type: web
    name: mohamed-portfolio
    runtime: python
    buildCommand: pip install -r requirements.txt && python seed.py
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
